name: Contrib CI Pipeline
on:
  workflow_dispatch:

jobs:
  CI:
    uses: ChrisLightfootWild/opentelemetry-php-contrib/.github/workflows/instrumentation-ext-rdkafka.yml@fix/ci/kafka
    with:
      package-root: '.'
